name: TAIFEX 資料爬蟲

on:
  schedule:
    # 每個交易日下午 3:05 執行 (UTC+8 = UTC 07:05)
    - cron: '5 7 * * 1-5'
  # 允許手動觸發
  workflow_dispatch:

jobs:
  crawl-and-import:
    runs-on: ubuntu-latest
    
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3
      
      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: 安裝 Python 依賴套件
        run: |
          python -m pip install --upgrade pip
          pip install pandas lxml requests pymongo

      - name: 爬取資料並保存到暫存目錄
        run: python taifex_pc_ratio_crawler.py
      
      - name: 顯示爬取結果摘要
        run: |
          echo "===== 爬取結果摘要 ====="
          ls -la data/
          echo "===== 資料預覽（前 20 行）====="
          head -n 20 data/pc_ratio_latest.json || echo "找不到最新資料文件"
      
      - name: 設定 Node.js 環境
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: 安裝 Node.js 依賴套件
        run: npm install
      
      - name: 將資料導入 MongoDB
        run: node import_taifex_data.js
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      
      # 使用 GitHub Actions 日誌功能記錄執行結果
      - name: 記錄執行結果
        run: |
          echo "爬蟲和資料導入已完成"
          echo "時間: $(date)"
          echo "最新資料檔案大小: $(du -h data/pc_ratio_latest.json | cut -f1)"
